export const columnsDefinition = [
  {
    field: 'study_number',
    headerName: 'Study Number',
    type: 'text',
    sortable: 'true',
    department: 'STUDY',
    freeze: 'true',
    editable: true,
    cellEditor: 'agTextCellEditor',
  },
  {
    field: 'sponsor_name',
    headerName: 'Sponsor',
    type: 'text',
    sortable: 'true',
    department: 'MAIL COMMUNICATION',
    freeze: 'true',
  },
  {
    field: 'sd_name',
    headerName: 'Study Director',
    type: 'text',
    sortable: 'true',
    department: 'STUDY',
    freeze: 'true',
  },
  {
    field: 'test_name',
    headerName: 'Test Name',
    type: 'text',
    sortable: false,
    department: 'MAIL COMMUNICATION',
  },
  {
    field: 'study_title',
    headerName: 'Study Title',
    type: 'text',
    sortable: false,
    department: 'STUDY',
  },
  {
    field: 'sample_received_dttm',
    headerName: 'Sample received date',
    type: 'date',
    sortable: false,
    department: 'TICO',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      // Optional date picker parameters
      format: 'dd-mmm-yyyy', // Specify your desired date format
    },
  },
  {
    field: 'tids_received_dttm',
    headerName: 'TIDS received date',
    type: 'date',
    sortable: false,
    department: 'TICO',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'scope_approval_dttm',
    headerName: 'Scope approved date',
    type: 'date',
    sortable: false,
    department: 'TICO',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'tids_issued_to_yaminy',
    headerName: 'TIDS issued to TFM',
    type: 'date',
    sortable: false,
    department: 'MAIL COMMUNICATION',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd-mmm-yyyy',
    },
    valueParser: (date) => {
      // Convert date string to an array of dates
      return date ? [date] : [] // Ensure it returns an array
    },
    valueGetter: (params) => {
      // Return a formatted string of dates if it's an array
      return params.data.tids_issued_to_yaminy.join(', ') || '' // Display array as string
    },
  },
  {
    field: 'invoice_number',
    headerName: 'Invoice number',
    type: 'text',
    sortable: false,
    department: 'accounts',
  },
  {
    field: 'invoice_date',
    headerName: 'Invoice date',
    type: 'date',
    sortable: false,
    department: 'accounts',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'payment_received_in_percent',
    headerName: 'Payment received In %',
    type: 'text',
    sortable: false,
    department: 'accounts',
  },
  {
    field: 'scope',
    headerName: 'Scope',
    type: 'text',
    sortable: false,
    department: 'SD',
  },
  {
    field: 'direct_reports',
    headerName: 'Direct Reports',
    type: 'text',
    sortable: false,
    department: 'MAIL COMMUNICATION',
  },
  {
    field: 'sd_allotment_TFM_to_qa',
    headerName: 'SD allotment TFM issued to QA',
    type: 'date',
    sortable: false,
    department: 'EDP',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'study_alloted_to_qa',
    headerName: 'Study alloted by QA (Date & Time)',
    type: 'date',
    sortable: false,
    department: 'EDP',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'study_plan_prepared_by',
    headerName: 'Study plan prepared by',
    type: 'text',
    sortable: false,
    department: 'EDP',
  },
  {
    field: 'study_plan_prepared_on',
    headerName: 'Study plan prepared (Date)',
    type: 'date',
    sortable: false,
    department: 'EDP',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'study_plan_to_sd',
    headerName: 'Study plan haand over to SD (Date)',
    type: 'date',
    sortable: false,
    department: 'EDP',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'draft_study_plan_to_qa',
    headerName: 'Draft study plan sent to QA (Date & Time)',
    type: 'date',
    sortable: false,
    department: 'SD',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'draft_study_plan_to_TFM_by_qa',
    headerName: 'Draft study plan sent to TFM by QA (Date)',
    type: 'date',
    sortable: false,
    department: 'QA',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'draft_study_plan_to_sponsor',
    headerName: 'Draft study plan sent to Sponsor (Date)',
    type: 'date',
    sortable: false,
    department: 'MAIL COMMUNICATION',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'draft_study_plan_sponsor_approval_comments_received',
    headerName: 'Study plan - Sponsor approval / comments received (Date)',
    type: 'date',
    sortable: false,
    department: 'MAIL COMMUNICATION',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'draft_study_plan_sponsor_approval_comments_sent_to_sd',
    headerName: 'Study plan Sponsor approval Comments sent to SD (Date)',
    type: 'date',
    sortable: false,
    department: 'MAIL COMMUNICATION',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'corrected_draft_study_plan_to_qa',
    headerName: 'Corrected draft study plan Sent to QA (Date & Time)',
    type: 'date',
    sortable: false,
    department: 'SD',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'corrected_draft_study_plan_to_TFM_by_qa',
    headerName: 'Corrected draft study plan sent to TFM (Date)',
    type: 'date',
    sortable: false,
    department: 'QA',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'corrected_draft_study_plan_to_sponsor',
    headerName: 'Corrected draft study plan Sent to Sponsor (Date)',
    type: 'date',
    sortable: false,
    department: 'MAIL COMMUNICATION',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'approval_for_corrected_draft_study_plan_received',
    headerName: 'Approval for Corrected draft study plan Received (Date)',
    type: 'date',
    sortable: false,
    department: 'MAIL COMMUNICATION',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'corrected_draft_study_plan_comments_to_sd',
    headerName: 'Corrected draft study plan Comments Sent to SD (Date)',
    type: 'date',
    sortable: false,
    department: 'MAIL COMMUNICATION',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'definitive_study_plan_taken',
    headerName: 'Definitive study plan taken (Date)',
    type: 'date',
    sortable: false,
    department: 'EDP',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'definitive_study_plan_sent_to_qa',
    headerName: 'Definitive study plan sent to QA (Date)',
    type: 'date',
    sortable: false,
    department: 'EDP',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'definitive_study_plan_to_TFM_by_qa',
    headerName: 'Definitive study plan Sent to TFM (Date)',
    type: 'date',
    sortable: false,
    department: 'QA',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'definitive_plan_to_sponsor',
    headerName: 'Definitive study plan sent to Sponsor (Date)',
    type: 'date',
    sortable: false,
    department: 'MAIL COMMUNICATION',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'definitive_study_plan_sponsor_approval',
    headerName: 'Definitive study plan sponsor approval received (Date)',
    type: 'date',
    sortable: false,
    department: 'MAIL COMMUNICATION',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'definitive_study_plan_comments_to_sd',
    headerName: 'Definitive study plan comments sent to SD (Date)',
    type: 'date',
    sortable: false,
    department: 'MAIL COMMUNICATION',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'study_initiation',
    headerName: 'Study Initiation (Date)',
    type: 'date',
    sortable: false,
    department: 'SD',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'experiment_start_date',
    headerName: 'Exp Start (Date)',
    type: 'date',
    sortable: false,
    department: 'SD',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'experiment_complete_date',
    headerName: 'Exp Completed (Date)',
    type: 'date',
    sortable: false,
    department: 'SD',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'draft_report_commited_to_qa',
    headerName: 'Draft report committed to QA (Date)',
    type: 'date',
    sortable: false,
    department: 'SD',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'draft_report_commited_to_sponsor',
    headerName: 'Draft report committed to Sponsor (Date)',
    type: 'date',
    sortable: false,
    department: 'SD',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'draft_report_completion',
    headerName: 'Draft report completion (Date)',
    type: 'date',
    sortable: false,
    department: 'SD',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'draft_report_to_qa',
    headerName: 'Draft report to QA (Date)',
    type: 'date',
    sortable: false,
    department: 'SD',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'draft_report_to_TFM_by_qa',
    headerName: 'Draft report sent to TFM (Date)',
    type: 'date',
    sortable: false,
    department: 'QA',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'draft_report_to_sponsor',
    headerName: 'Draft report sent to Sponsor (Date)',
    type: 'date',
    sortable: false,
    department: 'MAIL COMMUNICATION',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'draft_report_sponsor_reply',
    headerName: 'Draft report Sponsor Approval / Comments received (Date)',
    type: 'date',
    sortable: false,
    department: 'MAIL COMMUNICATION',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'draft_report_comments_to_sd',
    headerName: 'Draft Report Sponsor Approval Comments sent to SD (Date)',
    type: 'date',
    sortable: false,
    department: 'MAIL COMMUNICATION',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'corrected_draft_report_to_qa',
    headerName: 'Corrected draft report sent to QA (Date & Time)',
    type: 'date',
    sortable: false,
    department: 'SD',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'corrected_draft_report_to_TFM_by_qa',
    headerName: 'Corrected draft report sent to TFM (Date)',
    type: 'date',
    sortable: false,
    department: 'QA',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'corrected_draft_report_to_sponsor',
    headerName: 'Corrected draft report sent to Sponsor (Date)',
    type: 'date',
    sortable: false,
    department: 'MAIL COMMUNICATION',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'corrected_draft_report_sponsor_reply',
    headerName: 'Corrected draft report sponsor approval received (Date)',
    type: 'date',
    sortable: false,
    department: 'MAIL COMMUNICATION',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'corrected_draft_report_comments_to_sd',
    headerName: 'Corrected draft report comments sent to SD (Date)',
    type: 'date',
    sortable: false,
    department: 'MAIL COMMUNICATION',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'study_completion',
    headerName: 'Study Completion (Date)',
    type: 'date',
    sortable: false,
    department: 'SD',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'final_report_taken',
    headerName: 'Final Report taken',
    type: 'date',
    sortable: false,
    department: 'EDP',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'final_report_to_qa',
    headerName: 'Final report to QA',
    type: 'date',
    sortable: false,
    department: 'EDP',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'final_report_to_TFM',
    headerName: 'Final report to TFM',
    type: 'date',
    sortable: false,
    department: 'QA',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'final_invoice',
    headerName: 'Final Invoice (Date)',
    type: 'date',
    sortable: false,
    department: 'accounts',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'final_report_to_sponsor',
    headerName: 'Final Report to Sponsor (Date)',
    type: 'date',
    sortable: false,
    department: 'MAIL COMMUNICATION',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
  {
    field: 'hard_copies_sent',
    headerName: 'Hard Copies sent (Date)',
    type: 'date',
    sortable: false,
    department: 'EDP',
    editable: true,
    cellEditor: 'agDateCellEditor',
    cellEditorParams: {
      format: 'dd mmm yyyy',
    },
  },
]
